server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://10.222.22.77:8761/eureka/,http://146.222.43.26:8888/eureka/
spring:
  application:
    name: GALLERY-USER-SERVICE
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false