server:
  port: 9990
spring:
  application:
    name: GALLERY-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JiaJunLee/gallery-cloud.git
          searchPaths: gallery-config/{application}
          default-label: security-1.0