server:
  port: 6002
spring:
  rabbitmq:
     host: libu2-w10.corp.oocl.com
     port: 5672
     username: guest
     password: guest
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true