server:
  port: 6004
eureka:
  client:
    service-url:
      defaultZone: http://10.222.22.77:8761/eureka/,http://146.222.43.26:8888/eureka/
  instance:
    hostname: 10.222.22.77
spring:
  application:
    name: GALLERY-TURBINE
turbine:
  appConfig: GALLERY-USER-SERVICE,GALLERY-IMAGE-SERVICE
  clusterNameExpression: "'default'"