server:
  port: 6003
spring:
  rabbitmq:
     host: zha-mvp-007-w7
     port: 5672
     username: gallery
     password: 123456
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true