spring:
  profiles: kevin
eureka:
  instance:
    hostname: caike3-w10.corp.oocl.com
  client:
    service-url: http://libu2-w10.corp.oocl.com:8761/eureka/,http://liuju7-w10.corp.oocl.com:8761/eureka/