spring:
  profiles: burgess
eureka:
  instance:
    hostname: libu2-w10.corp.oocl.com
  client:
    service-url: http://liuju7-w10.corp.oocl.com:8761/eureka/,http://caike3-w10.corp.oocl.com:8761/eureka/