server:
  port: 6100
spring:
  rabbitmq:
     host: zha-mvp-007-w7
     port: 5672
     username: gallery
     password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://libu2-w10.corp.oocl.com:8761/eureka/,http://caike3-w10.corp.oocl.com:8761/eureka/,http://liuju7-w10.corp.oocl.com:8761/eureka/,http://localhost:8761/eureka/
turbine:
  appConfig: GALLERY-USER-SERVICE,GALLERY-IMAGE-SERVICE,GALLERY-FILE-SERVICE
  clusterNameExpression: "'default'"