spring:
  rabbitmq:
     host: zha-mvp-007-w7
     port: 5672
     username: gallery
     password: 123456
   data:
       mongodb:
          database: gallery
          host: zha-mvp-007-w7
          port: 27017
   jackson:
       time-zone: GMT+8
security.jwt.secret: otherpeopledontknowit