server:
  port: 6111
spring:
  rabbitmq:
     host: libu2-w10.corp.oocl.com
     port: 5672
     username: guest
     password: guest
  data:
     mongodb:
        database: gallery-test
        host: libu2-w10.corp.oocl.com
        port: 27017
  jackson:
     time-zone: GMT+8
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false
