server:
  port: 6001
spring:
  rabbitmq:
     host: zha-mvp-007-w7.corp.oocl.com
     port: 5672
     username: gallery
     password: 123456
  data:
     mongodb:
        database: gallery
        host: zha-mvp-007-w7.corp.oocl.com
        port: 27017
  jackson:
     time-zone: GMT+8
feign:
  hystrix:
     enabled: true
management:
  security:
     enabled: false

