server:
  port: 6001
spring:
  rabbitmq:
     host: libu2-w10.corp.oocl.com
     port: 5672
     username: guest
     password: guest
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false