spring:
  application:
    name: GALLERY-EUREKA
server:
  port: 8761
management:
  security:
    enabled: false
---
spring:
  profiles: burgess
eureka:
  instance:
    hostname: libu2-w10.corp.oocl.com
  client:
    service-url: http://liuju7-w10.corp.oocl.com:8761/eureka/,http://caike3-w10.corp.oocl.com:8761/eureka/
---
spring:
  profiles: kevin
eureka:
  instance:
    hostname: caike3-w10.corp.oocl.com
  client:
    service-url: http://libu2-w10.corp.oocl.com:8761/eureka/,http://liuju7-w10.corp.oocl.com:8761/eureka/
---
spring:
  profiles: justin
eureka:
  instance:
    hostname: liuju7-w10.corp.oocl.com
  client:
    service-url: http://libu2-w10.corp.oocl.com:8761/eureka/,http://caike3-w10.corp.oocl.com:8761/eureka/